esphome:
  name: tank_depth_sensor
  platform: ESP8266
  board: nodemcuv2
  platformio_options:
    upload_speed: 921600

wifi:
  ssid: !secret ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Tank Depth Sensor esp32"
    password: !secret wifi_password

captive_portal:

# Enable logging
logger:

# Enable Home Assistant API
api:

ota:

# 0%   - 32 ohm
# 100% - 233 ohm
# 0%   - 2.31v (with 100ohm resistor)
# 100% - 0.8v  (with 100ohm resistor)

# esphome readings
# 0%   - 29.5 ohm
# 100% - 8.5 ohm

sensor:
  - platform: resistance
    sensor: source_sensor
    configuration: DOWNSTREAM
    resistor: 100Ohm
    name: Tank Depth Sensor
    id: resistance_sensor

# Example source sensor:
  - platform: adc
    id: source_sensor
    pin: A0
    update_interval: 10s

  - platform: template
    name: "Tank Depth Percent"
    id: tank_depth_percent
    icon: "mdi:water-percent"
    unit_of_measurement: "%"
    update_interval: 10s
    accuracy_decimals: 0
    lambda: |-
      return id(resistance_sensor).state;
    filters:
      - calibrate_linear:
          - 29.5 -> 0.0
          - 8.50 -> 100.0

  - platform: dht
    pin: D1
    temperature:
      name: "Indoor Garden Temperature"
      filters:
      - lambda: return x * (9.0/5.0) + 32.0;
      unit_of_measurement: "°F"
    humidity:
      name: "Indoor Garden Humidity"
    update_interval: 60s